### PR TITLE
Update attempt_feedback.html

### PR DESCRIPTION
**Pull request by spidersouris**
http://forum.wordreference.com/threads/fr-space-before-a-colon-semicolon-question-mark-or-exclamation-point.54376/

### CODE REVIEW

**Comment by larose** [comment]
Thanks for the patch! I agree for the non-breaking space before the colon. However, in Québec, we don't put a space before an exclamation mark!

I'll merge your pull request if you remove the space before the exclamation mark :)

**Comment by spidersouris** [comment]
oh ok, alright!

**Comment by larose** [comment]
Can you squash your commits? Apparently you can do it from the web interface (https://github.com/blog/2141-squash-your-commits). Otherwise, I'll do it from the cli.

**Comment by spidersouris** [comment]
I think you're the only one who can do it.

http://i.stack.imgur.com/y3JEz.png

**Comment by larose** [comment]
I did it from the command line.

**Pull request closed without merging**
